import { useState } from 'react'
import { AnimatePresence, motion, useReducedMotion } from 'motion/react'
import { BrowserRouter, Link, NavLink, Route, Routes, useLocation } from 'react-router-dom'

const collections = [
  { number: '01', title: 'Interstate', year: '2024', place: 'Across I-70', image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=85' },
  { number: '02', title: 'Low Country', year: '2023', place: 'Beaufort, SC', image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1600&q=85' },
  { number: '03', title: 'Vacancy', year: '2022', place: 'Tucson, AZ', image: 'https://images.unsplash.com/photo-1487958449943-2429e8be8625?auto=format&fit=crop&w=1600&q=85' },
  { number: '04', title: 'Kin', year: '2024', place: 'Kentucky', image: 'https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=1600&q=85' },
  { number: '05', title: 'Static', year: '2021', place: 'West Texas', image: 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1600&q=85' },
  { number: '06', title: 'Coastline', year: '2023', place: 'Outer Banks', image: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1600&q=85' },
]
const rise = { hidden: { opacity: 0, y: 24 }, visible: { opacity: 1, y: 0 } }
const t = { duration: .8, ease: [0.16, 1, .3, 1] }

function Shell({ children }) {
  const [open, setOpen] = useState(false)
  const location = useLocation()
  const reduce = useReducedMotion()
  return <main className="min-h-screen overflow-hidden bg-ink text-paper selection:bg-acid selection:text-ink">
    <header className="fixed inset-x-0 top-0 z-50 flex items-center justify-between px-5 py-5 mix-blend-difference md:px-10">
      <Link to="/" className="font-mono text-[11px] uppercase tracking-[.22em]">Mac Motz</Link>
      <nav className="hidden gap-8 font-mono text-[10px] uppercase tracking-[.18em] md:flex"><Nav to="/portfolio">Portfolio</Nav><Nav to="/about">About</Nav><Nav to="/contact">Contact</Nav></nav>
      <button className="font-mono text-[10px] uppercase tracking-[.18em] md:hidden" onClick={() => setOpen(!open)} aria-expanded={open}>Menu</button>
    </header>
    <AnimatePresence>{open && <motion.nav initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-40 grid place-content-center gap-7 bg-ink text-center font-display text-5xl" onClick={() => setOpen(false)}><Link to="/portfolio">Portfolio</Link><Link to="/about">About</Link><Link to="/contact">Contact</Link></motion.nav>}</AnimatePresence>
    <AnimatePresence mode="wait"><motion.div key={location.pathname} initial={{ opacity: 0, y: reduce ? 0 : 12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} transition={reduce ? { duration: 0 } : { duration: .45 }}>{children}</motion.div></AnimatePresence>
  </main>
}
function Nav({ to, children }) { return <NavLink to={to} className={({isActive}) => `transition hover:text-acid ${isActive ? 'text-acid' : ''}`}>{children}</NavLink> }
function Eyebrow({ children }) { return <p className="font-mono text-[10px] uppercase tracking-[.2em] text-acid">{children}</p> }

function Home() { const reduce = useReducedMotion(); return <>
  <section className="relative min-h-screen px-5 pt-28 md:px-10"><motion.div initial="hidden" animate="visible" variants={{visible:{transition:{staggerChildren:.12}}}} className="relative z-10 flex min-h-[calc(100vh-7rem)] flex-col justify-between"><div className="flex justify-between font-mono text-[10px] uppercase tracking-[.18em] text-paper/60"><span>Selected photographs</span><span>2018—2026</span></div><div className="max-w-6xl"><motion.div variants={rise} transition={t}><Eyebrow>Mac Motz / photographer</Eyebrow></motion.div><motion.h1 variants={rise} transition={t} className="mt-6 font-display text-[18vw] leading-[.78] tracking-[-.07em] md:text-[13vw]">The distance<br/>between places.</motion.h1></div><motion.div variants={rise} transition={t} className="flex justify-between border-t border-paper/25 pt-4 font-mono text-[10px] uppercase tracking-[.18em]"><span>Scroll to explore</span><span className="text-paper/55">Field notes in light & landscape</span></motion.div></motion.div><motion.div initial={{clipPath:'inset(100% 0 0 0)'}} animate={{clipPath:'inset(0 0 0 0)'}} transition={{...t, duration:reduce?0:1.35}} className="absolute inset-x-0 bottom-0 h-[47vh] bg-[url('https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=2000&q=85')] bg-cover bg-center opacity-45"><div className="absolute inset-0 bg-gradient-to-t from-ink via-transparent to-ink/40"/></motion.div></section>
  <section className="px-5 py-28 md:px-10 md:py-40"><div className="mb-16 flex items-end justify-between"><Eyebrow>Selected collections</Eyebrow><Link to="/portfolio" className="font-mono text-[10px] uppercase tracking-[.16em] text-paper/60 hover:text-acid">View all work ↗</Link></div><div className="grid gap-x-5 gap-y-18 md:grid-cols-12 md:gap-y-28">{collections.slice(0,4).map((item,i)=><CollectionCard key={item.title} item={item} i={i}/>)}</div></section>
  <section className="border-y border-paper/20 px-5 py-28 md:px-10 md:py-40"><div className="grid gap-12 md:grid-cols-12"><Eyebrow>About the work</Eyebrow><div className="md:col-span-8"><p className="font-display text-4xl leading-[1.03] tracking-[-.04em] md:text-7xl">Photographs made around the edges of ordinary life: places passed through, rooms emptied, and family gathered at the end of the day.</p><Link to="/about" className="mt-12 inline-block border-b border-acid pb-2 font-mono text-[10px] uppercase tracking-[.2em] text-acid">More about Mac ↗</Link></div></div></section>
  <ContactStrip /></> }

function Portfolio() { const [filter,setFilter]=useState('All'); const visible=filter==='All'?collections:collections.filter(x=>x.title===filter); return <section className="px-5 pb-28 pt-36 md:px-10 md:pt-44"><Eyebrow>Archive / 06 collections</Eyebrow><h1 className="mt-5 font-display text-[15vw] leading-[.8] tracking-[-.07em] md:text-[11vw]">All work.</h1><div className="mt-16 flex flex-wrap gap-x-5 gap-y-3 border-y border-paper/20 py-4 font-mono text-[10px] uppercase tracking-[.14em]">{['All',...collections.map(x=>x.title)].map(x=><button key={x} onClick={()=>setFilter(x)} className={filter===x?'text-acid':'text-paper/55 hover:text-paper'}>{x}</button>)}</div><motion.div layout className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{visible.map((item,i)=><motion.article layout initial={{opacity:0}} animate={{opacity:1}} key={item.title} className={i%5===0?'sm:col-span-2 lg:col-span-2':''}><CollectionCard item={item} i={i} large /></motion.article>)}</motion.div></section> }

function About() { return <section className="px-5 pb-28 pt-36 md:px-10 md:pt-44"><div className="grid gap-14 md:grid-cols-12"><div className="md:col-span-3"><Eyebrow>About Mac Motz</Eyebrow><p className="mt-6 font-mono text-[10px] uppercase leading-loose tracking-[.15em] text-paper/55">Based in the United States<br/>Available for assignments</p></div><div className="md:col-span-8"><h1 className="font-display text-5xl leading-[.96] tracking-[-.05em] md:text-8xl">Looking closely at what remains.</h1><div className="mt-16 grid gap-10 border-t border-paper/20 pt-6 text-lg leading-relaxed text-paper/75 md:grid-cols-2"><p>Mac Motz is a photographer interested in the quiet evidence of people moving through the world. The work begins with place and stays long enough to notice what is easily missed.</p><p>Across landscapes, roadside rooms, and family archives, each series considers the distance between memory and the present moment.</p></div><div className="mt-20 grid gap-5 border-t border-paper/20 pt-6 font-mono text-[10px] uppercase tracking-[.15em] text-paper/60 md:grid-cols-3"><span>Selected exhibitions<br/><b className="mt-2 block font-normal text-paper">2022—2026</b></span><span>Press & publications<br/><b className="mt-2 block font-normal text-paper">Available on request</b></span><span>Inquiries<br/><a className="mt-2 block text-acid" href="mailto:hello@macmotz.com">hello@macmotz.com</a></span></div></div></div></section> }

function Contact() { const [sent,setSent]=useState(false); function submit(e){e.preventDefault();setSent(true)} return <section className="px-5 pb-28 pt-36 md:px-10 md:pt-44"><div className="grid gap-14 md:grid-cols-12"><div className="md:col-span-4"><Eyebrow>Inquiries & collaborations</Eyebrow><h1 className="mt-5 font-display text-5xl leading-[.95] tracking-[-.05em] md:text-7xl">Begin a conversation.</h1><p className="mt-8 max-w-sm text-paper/60">For commissions, exhibitions, licensing, and all other questions, use the form or email directly.</p><a href="mailto:hello@macmotz.com" className="mt-8 block font-mono text-[10px] uppercase tracking-[.15em] text-acid">hello@macmotz.com ↗</a></div><div className="md:col-span-7 md:col-start-6"><AnimatePresence mode="wait">{sent?<motion.div key="thanks" initial={{opacity:0}} animate={{opacity:1}} className="border-y border-paper/20 py-16"><Eyebrow>Message prepared</Eyebrow><p className="mt-5 font-display text-4xl">Thank you. Mac will be in touch soon.</p><button onClick={()=>setSent(false)} className="mt-10 font-mono text-[10px] uppercase tracking-[.15em] text-acid">Send another message</button></motion.div>:<motion.form key="form" initial={{opacity:0}} animate={{opacity:1}} onSubmit={submit} className="space-y-9"><Field label="Name" required/><Field label="Email" type="email" required/><Field label="What can we help with?"/><label className="block"><span className="font-mono text-[10px] uppercase tracking-[.16em] text-paper/55">Message</span><textarea required rows="4" className="mt-4 w-full resize-none border-b border-paper/30 bg-transparent py-3 outline-none transition focus:border-acid" /></label><button className="group inline-flex items-center gap-5 font-mono text-[10px] uppercase tracking-[.17em] text-acid">Send inquiry <span className="text-xl transition group-hover:translate-x-2">→</span></button><p className="font-mono text-[9px] uppercase tracking-[.12em] text-paper/40">Demo form: connect an email service before launch.</p></motion.form>}</AnimatePresence></div></div></section> }
function Field({label,type='text',required}) { return <label className="block"><span className="font-mono text-[10px] uppercase tracking-[.16em] text-paper/55">{label}</span><input type={type} required={required} className="mt-4 w-full border-b border-paper/30 bg-transparent py-3 text-lg outline-none transition focus:border-acid" /></label> }
function CollectionCard({item,i,large}) { const reduce=useReducedMotion(); return <motion.article initial={{opacity:0,y:reduce?0:36}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.2}} transition={{...t,delay:reduce?0:i*.06}} className={large?'':'md:col-span-6'}><Link to="/contact" className="group block"><div className="relative aspect-[4/5] overflow-hidden bg-paper/10"><img src={item.image} alt={`${item.title}, ${item.place}`} className="h-full w-full object-cover grayscale transition duration-700 group-hover:scale-105 group-hover:grayscale-0"/><div className="absolute inset-0 bg-gradient-to-t from-ink/65 via-transparent to-transparent"/><span className="absolute left-4 top-4 font-mono text-[10px] tracking-[.16em]">{item.number}</span><span className="absolute bottom-4 right-4 font-mono text-[10px] tracking-[.16em] opacity-0 transition group-hover:opacity-100">VIEW SERIES ↗</span></div><div className="mt-4 flex items-baseline justify-between"><h2 className="font-display text-3xl tracking-[-.04em]">{item.title}</h2><p className="font-mono text-[10px] uppercase tracking-[.14em] text-paper/55">{item.place} / {item.year}</p></div></Link></motion.article> }
function ContactStrip(){ return <section className="px-5 py-28 md:px-10 md:py-40"><Eyebrow>Contact</Eyebrow><Link to="/contact" className="mt-6 block font-display text-[13vw] leading-[.82] tracking-[-.07em] md:text-[10vw]">Start a<br/>conversation <span className="text-acid">↗</span></Link><footer className="mt-28 flex flex-col justify-between gap-5 border-t border-paper/20 pt-5 font-mono text-[10px] uppercase tracking-[.15em] text-paper/55 md:flex-row"><span>© 2026 Mac Motz</span><span>Photographer / USA</span><a href="#top">Back to top ↑</a></footer></section> }

export default function App(){ return <BrowserRouter><Shell><Routes><Route path="/" element={<Home/>}/><Route path="/portfolio" element={<Portfolio/>}/><Route path="/about" element={<About/>}/><Route path="/contact" element={<Contact/>}/><Route path="*" element={<Home/>}/></Routes></Shell></BrowserRouter> }
